---
version: "3"
services:
  mysql:
    image: mysql:5.7.38
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test1234
    ports:
      - 3308:3306
    volumes:
      - ./docker/db/sql:/docker-entrypoint-initdb.d

